# Generated by Django 3.1.1 on 2021-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210305_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
