# Generated by Django 3.1.1 on 2021-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_addresses_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ordered_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
