# Generated by Django 3.1.1 on 2021-03-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210321_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='ordered_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_amount',
            field=models.IntegerField(default=0),
        ),
    ]
