# Generated by Django 3.1.1 on 2021-04-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210329_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.JSONField(default=dict),
        ),
    ]
