# Generated by Django 3.1.1 on 2021-04-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_delivery_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_datetime',
        ),
    ]
